FROM python:3.5

WORKDIR /app/

ADD requirements/*.txt /app/requirements/

ARG SSH_PRIVATE_KEY

RUN eval "$(ssh-agent -s)" &&\
    echo "$SSH_PRIVATE_KEY" | ssh-add - &&\
    mkdir -p ~/.ssh &&\
    echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config &&\
    pip install -r /app/requirements/production.txt
